---
abstract: 'REST Controller for [% schema_class %]'
author:
  - 'Amiri Barksdale <amiri@arisdottle.net>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Controller::DBIC::API::REST: 0
  Catalyst::Helper: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Utils: 0
  DBIx::Class::Core: 0
  DBIx::Class::ResultSet: 0
  DBIx::Class::Schema: 0
  English: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Path: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  JSON::XS: 0
  Test::Deep: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  URI: 0
  base: 0
  bytes: 0
  parent: 0
  perl: 5.6.0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-Controller-DBIC-API-REST
requires:
  File::Spec: 0
  FindBin: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/amiri/Catalyst-Helper-Controller-DBIC-API-REST-0.01/issues
  repository: git://github.com/amiri/Catalyst-Helper-Controller-DBIC-API-REST-0.01.git
version: 0.08
