---
abstract: ~
author:
  - 'Amiri Barksdale <amiri@metalabel.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Helper-Controller-DBIC-API-REST
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Catalyst::Controller::DBIC::API: 0
  Catalyst::Controller::DBIC::API::REST: 0
  Catalyst::Helper: 0
  Filter::Util::Call: 0
  Module::Load: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
